# Generated by Django 5.2.9 on 2026-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.TextField()),
                ('from_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('from_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_address', models.TextField()),
                ('to_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('to_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_price', models.PositiveIntegerField(default=0)),
                ('final_price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Haydovchi kutilmoqda'), ('accepted', 'Haydovchi qabul qildi'), ('in_progress', 'Safar boshlandi'), ('completed', 'Safar tugadi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
